name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push AI Backend
        uses: docker/build-push-action@v5
        with:
          context: ./ai-backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ai-backend:latest

      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

      - name: SSH into Master and Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd k8s-deployment || git clone https://github.com/${{ github.repository }} k8s-deployment
            cd k8s-deployment
            git pull origin main
            kubectl apply -f k8s/configmap.yml
            kubectl apply -f k8s/longhorn-storageclass.yaml
            kubectl apply -f k8s/postgres.yml
            kubectl apply -f k8s/deploy.yml
            kubectl apply -f k8s/longhorn-ui-nodeport.yaml
            kubectl apply -f k8s/servicemonitor.yml
            kubectl apply -f k8s/frontend-ingress.yml
            kubectl apply -f k8s/monitoring-ingress.yml
            kubectl rollout restart deployment ai-backend
            kubectl rollout restart deployment backend
            kubectl rollout restart deployment frontend
